version: "3.8"

services:
  postgres15:
    image: postgres:15
    container_name: postgres15
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: guident
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  guident_redis:
    image: redis:latest
    container_name: guident_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local
